modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory
issueTrackerURL="https://github.com/FifouBE/EconomyInc/issues" #optional
credits="FifouBE" #optional
[[mods]] #mandatory
modId="economyinc" #mandatory
version="1.6.8" #mandatory
displayName="Economy Inc." #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/economy-inc" #optional
description='''
DESCRIPTION
'''